.TH FLYBINDS 1 flybinds\-VERSION
.SH NAME
flybinds \- visual keychords in Xorg
.SH SYNOPSIS
.B flybinds
.RB [ \-bvh ]
.RB [ \-c
.IR columns ]
.RB [ \-fn
.IR font ]
.RB [ \-m
.IR monitor ]
.RB [ \-s
.IR separator ]
.RB [ \-bg
.IR color ]
.RB [ \-kf
.IR color ]
.RB [ \-sf
.IR color ]
.RB [ \-df
.IR color ]
.RB [ \-bc
.IR color ]
.RB [ \-cs
.IR separation ]
.RB [ \-ph
.IR paddingH ]
.RB [ \-pv
.IR paddingV ]
.RB [ \-pt
.IR titlepadding ]
.RB [ \-bw
.IR border width ]
.RB [ \-w
.IR windowid ]
.IR key1
.IR key2 " ..."
.SH DESCRIPTION
.B flybinds 
Keychord utility for Xorg, which displays a popup helper indicating the possibilities. Similar to which-key support in Emacs. It can be launched
without parameters to go to the root or with some leading paramenters and flybinds
will be launched as if you had pressed key1, then key2, ...
.SH OPTIONS
.TP
.B \-b
appears at the bottom of the screen.
.TP
.B \-v
displays version.
.TP
.B \-h
display help message.
.TP
.B \-c " columns"
maximum number of columns to be displayed.
.TP
.B \-c " separator"
separator used ('->', ':', '', ...)
.TP
.BI \-bg " color"
background color.
.TP
.BI \-fk " color"
foreground color for the key name.
.TP
.BI \-fs " color"
foreground color for the separator.
.TP
.BI \-fd " color"
foreground color for the description.
.TP
.BI \-bc " color"
border color.
.TP
.BI \-cs " separation"
column separation.
.TP
.BI \-ph " paddingH"
padding for left and right sides.
.TP
.BI \-pv " paddingV"
padding for up and down sides.
.TP
.BI \-pt " titlepadding"
padding-top for title sections
.TP
.BI \-bw " width"
border width.
.SH USAGE
When launched, it will show a menu with items. To navigate to an item, just press the key it indicates. If that item is another menu, this will be shown. Otherwise, the specific script will be handled.
.P
flybinds can be launched with options (flybinds key1 key2 ...). This way, when launched, it will automatically navigate first to the item key1, then key2, etc.
.P
A final item can have a custom specific script to execute. However, if no script is specified, it will search up to the root the first script provided, and it will be launched that script with the keys needed to navigate to the final item needed.
.P
For example, suppose an item 'session' (s) has a child 'power' (p) that has the children 'poweroff' (p), 'reboot' (r) and 'suspend' (s). It's possible to set a script for the item 'session' (or 'power') but not for its final children. Then, if 'reboot' is pressed, the script for 'session' will be executed with the arguments 'p' 'r' ('session' -> (p)ower -> (r)eboot)
.SH CUSTOMIZATION
flybinds is customized by creating a custom config.h and (re)compiling the source code. This keeps it fast, secure and simple
.P
Appearance can be customized by changing the Xresources, as indicated in config.def.h, apart from the command line arguments explained in section OPTIONS.
.SH SEE ALSO
.IR dmenu (1),
.IR sxhkd (1)
