static Key keys[] = {
    /* special */
    { 0, XK_space,  "␣"   },
    { 0, XK_Return, "\\n" },
    { 0, XK_period, "."   },
    { 0, XK_comma,  ","   },
    { 0, XK_plus,   "+"   },
    { 0, XK_minus,  "-"   },

    /* numbers */
    { 0, XK_0, "0" },
    { 0, XK_1, "1" },
    { 0, XK_2, "2" },
    { 0, XK_3, "3" },
    { 0, XK_4, "4" },
    { 0, XK_5, "5" },
    { 0, XK_6, "6" },
    { 0, XK_7, "7" },
    { 0, XK_8, "8" },
    { 0, XK_9, "9" },

    /* lowercase */
    { 0, XK_a, "a" },
    { 0, XK_b, "b" },
    { 0, XK_c, "c" },
    { 0, XK_d, "d" },
    { 0, XK_e, "e" },
    { 0, XK_f, "f" },
    { 0, XK_g, "g" },
    { 0, XK_h, "h" },
    { 0, XK_i, "i" },
    { 0, XK_j, "j" },
    { 0, XK_k, "k" },
    { 0, XK_l, "l" },
    { 0, XK_m, "m" },
    { 0, XK_n, "n" },
    { 0, XK_o, "o" },
    { 0, XK_p, "p" },
    { 0, XK_q, "q" },
    { 0, XK_r, "r" },
    { 0, XK_s, "s" },
    { 0, XK_t, "t" },
    { 0, XK_u, "u" },
    { 0, XK_v, "v" },
    { 0, XK_w, "w" },
    { 0, XK_x, "x" },
    { 0, XK_y, "y" },
    { 0, XK_z, "z" },

    /* uppercase */
    { ShiftMask, XK_A, "A" },
    { ShiftMask, XK_B, "B" },
    { ShiftMask, XK_C, "C" },
    { ShiftMask, XK_D, "D" },
    { ShiftMask, XK_E, "E" },
    { ShiftMask, XK_F, "F" },
    { ShiftMask, XK_G, "G" },
    { ShiftMask, XK_H, "H" },
    { ShiftMask, XK_I, "I" },
    { ShiftMask, XK_J, "J" },
    { ShiftMask, XK_K, "K" },
    { ShiftMask, XK_L, "L" },
    { ShiftMask, XK_M, "M" },
    { ShiftMask, XK_N, "N" },
    { ShiftMask, XK_O, "O" },
    { ShiftMask, XK_P, "P" },
    { ShiftMask, XK_Q, "Q" },
    { ShiftMask, XK_R, "R" },
    { ShiftMask, XK_S, "S" },
    { ShiftMask, XK_T, "T" },
    { ShiftMask, XK_U, "U" },
    { ShiftMask, XK_V, "V" },
    { ShiftMask, XK_W, "W" },
    { ShiftMask, XK_X, "X" },
    { ShiftMask, XK_Y, "Y" },
    { ShiftMask, XK_Z, "Z" },
};
